### ISSUE TITLE
complete code share

### ISSUE THREAD

**Issue by Rimay** [yuanxiaosc/DeepNude-an-Image-to-Image-technology#2]
can you share the complete code of linux version or window version to novemberstan@gmail.com? with the dataset even better

**Comment by yuanxiaosc** [comment]
@Rimay You can use the search engine to find software related to DeepNude (the software author claims not to disclose the code). It is illegal to make pornographic software and distribute pornographic content in China, so I can't relate pornographic content. But if you want to get an image-to-image or even text-to-image related technology, I can provide technical and research support (including publishing papers) for a fee. 

你可以通过搜索引擎寻找DeepNude相关的软件（软件作者声称不会公开代码）。在中国制造色情软件和传播色情内容都属于违法行为，因此我不可能涉及色情相关内容。但是如果你想获取如何实现Image-to-image 甚至 text-to-image相关技术，我可以有偿的提供技术和研究支持（包括发表论文）。

**Comment by silentshotghost** [comment]
for a fee umm just google my github name on google and you will find what you need :)

**Comment by yuanxiaosc** [comment]
@silentshotghost Yes, the code of DeepNude has been published by the author and can be found through Google search. Please don't ask me for it.

**Comment by someoneAlready** [comment]
垃圾，在这招摇撞骗。。。。
