### ISSUE TITLE
蹭DeepNude的热点一点也不光彩

### ISSUE THREAD

**Issue by justfouw** [yuanxiaosc/DeepNude-an-Image-to-Image-technology#3]
要研究图像Image2Image的技术，就好好研究技术，做些有价值的事情。DeepNude不是什么好case  
[DeepFake和DeepNude：低级需求催生的AI应用是有原罪的](https://mp.weixin.qq.com/s/S5SfCD36YT9V3Jx6gdRdlg)

**Comment by LJXLJXLJX** [comment]
是的，纯属蹭热点骗star。

**Comment by v5-yu** [comment]
你已开通絕美胴畫周刊  妖媚蜜胸熟女前凸后翘勾魂摄魄 每期$15 回复TD退订


 
---原始邮件---
发件人: "Little star"<notifications@github.com>
发送时间: 2019年7月5日(星期五) 中午11:46
收件人: "yuanxiaosc/DeepNude-an-Image-to-Image-technology"<DeepNude-an-Image-to-Image-technology@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [yuanxiaosc/DeepNude-an-Image-to-Image-technology] 蹭DeepNude的热点一点也不光彩 (#3)



Closed #3.
